accommodation/accommodation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, handler400

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/',include('django.contrib.auth.urls')),
    path('owner/', include('owner.urls')),
    path('', include('property.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'property.views.error_404_view'

accommodation/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from .views import PasswordsChangeView

urlpatterns = [
    path('registration/', views.registration, name='user_registration'),
    path('login/', views.user_login, name='login'),
    # path('user_settings/', views.user_settings_view, name='user_settings'),
    path('change_your_password/',PasswordsChangeView.as_view(), name='change_your_password'),


    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

accommodation/owner/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
]

accommodation/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, first_name, last_name, phone_number, email, password=None):
        if not email:
            raise ValueError("User must have an email address")

        user = self.model(
            email = self.normalize_email(email),
            phone_number = phone_number,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    

    def create_superuser(self, email, password, first_name, last_name, phone_number):
        user = self.create_user(
            email = self.normalize_email(email),
            password = password,
            first_name = first_name,
            last_name = last_name,
            phone_number = phone_number,
        )

        user.is_admin   =   True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email               = models.EmailField(verbose_name='email', max_length=100, unique=True)
    first_name          = models.CharField(max_length=200)
    last_name           = models.CharField(max_length=200)
    phone_number        = models.CharField(max_length=10, unique=True)
    date_joined         = models.DateTimeField(verbose_name='data joined', auto_now_add=True)
    last_login          = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin            = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    is_staff            = models.BooleanField(default=False)
    is_superuser        = models.BooleanField(default=False)
    is_owner            = models.BooleanField(default=False)
    profile_pic         = models.ImageField(upload_to='profile_pic/', default="None")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number']

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_lable):
        return True

accommodation/account/forms.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

class PasswordChangeingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

accommodation/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, auth
from django.contrib.auth.views import PasswordChangeView
from .forms import PasswordChangeingForm
from django import forms
from django.core.validators import validate_email
from django.urls import reverse_lazy
# from pro.models import House
from django.contrib import messages
from .models import User


# Create your views here.
def user_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')    
    else:
        context = {}
        return render(request, 'login.html', context)

def registration(request):

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if  User.objects.filter(phone_number=phone_number).exists() and User.objects.filter(email=email).exists():
                messages.info(request,'Phone Number and Email are alredy exists') 
                return redirect('user_registration')  
            elif User.objects.filter(phone_number=phone_number).exists():
                messages.info(request,'Phone Number is alredy exists') 
                return redirect('user_registration')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'Email is alreay exists')
                return redirect('user_registration')
            else:   
                user = User.objects.create_user(
                                first_name=first_name,
                                last_name=last_name,
                                phone_number=phone_number,
                                email=email,
                                password=password,
                )
                user.save()
                print('user created')
                return redirect('login')
        
        else:
            messages.info(request,'Password not matching')
            return redirect('user_registration')        

        return redirect('login')
    else:
        context = {}
        return render(request, 'registration.html', context)

class PasswordsChangeView(PasswordChangeView):
    template_name = 'password_change.html'
    form_class = PasswordChangeingForm
    success_url = reverse_lazy('index')
    # success_url = reverse_lazy('password_success')



# def user_settings_view(request):
#     context = { }
#     return render(request, 'user_settings.html', context)

accommodation/account/templates/base_account.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="/static/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <style>
        .bg-dark {
            background-color: #1f2229;
        }

        .custom_input {
            background-color: #1f2229;
            border: solid 1px white;
            border-bottom: solid 1px white;
            color: white;
            width: 100%;
            font-size: medium;
            padding: 0px;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            color: #ffffff;
            font-family: 'Roboto', sans-serif;
            font-weight: 700;
            margin-top: 0;
            margin-bottom: 15px;
            letter-spacing: .025em;
            line-height: 1.6;
        }

        .custom_fount {
            color: gray;
        }
        span{
    position: absolute;
    right: 25px;
    transform: translate(0,-50%);
    top: 80%;
    cursor: pointer;
}
.fa{
    font-size: 20px;
    color: #7a797e;
}
.card {
    border-radius: 30px;
}
    </style>
</head>

<body style="background-color: black;">
    <!-- Just an image -->
    <nav class="navbar" style="background-color: #181818;">
        <a class="navbar-brand" href="#">
            <img src="/static/images/logo-blue.png" width="40%" height="30" alt="logo" class="img-fluid">
        </a>
    </nav>

    {% block account_content %}
    
    {% endblock %}

</body>
<script>
    var state = false;
    function toggle() {
        if (state) {
            document.getElementById("password").setAttribute("type", "password");
            document.getElementById("eye").style.color = '#7a797e';
            state = false;
        }
        else {
            document.getElementById("password").setAttribute("type", "text");
            document.getElementById("eye").style.color = '#5887ef';
            state = true;
        }
    }
</script>
</html>

accommodation/account/templates/login.html
{% extends 'base_account.html' %}

{% block account_content %}



<div class="error-section mt-100 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3  error-text text-center">
                <div class="error-content">
                    {% for message in messages %}
                    <div class="card" style="border-color: #c40000; height: 15%; background-color: black;">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-2">
                                    <img class="img-fluid" src="/static/images/warning.png" alt="...">
                                </div>
                                <div class="col-md-10">
                                    <h8 style="color: #c40000;">There was a problem</h8><br>
                                    <h8 style="color: red;">{{message}}</h8>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    {% endfor %}

                </div>
                <div class="error-search-container">
                    <div class="card text-light" style="background-color: #1f2229;">
                        <div class="card-body">
                            <h4>Login</h4>
                            {{email_msg}}
                            <hr />
                            <form id="login-form" action="#" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="text" name='email' id="email" tabindex="1" class="custom_input"
                                                value="" required="">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" name="password" id="password" tabindex="2" class="custom_input">
                                                <span>
                                                    <i class="fa fa-eye" id="eye" onclick="toggle()">
                                                    </i>
                                                </span>
                                        </div>
                                    </div>
                                    <div class="col-md-2"></div>
                                </div>
                                <div class="res-box text-center mt-10" style="padding-left: 10%;">
                                    <button type="submit" class="btn v1" style="width: 50%;"><span
                                            class="lnr lnr-exit"></span> Log In</button>
                                </div><br>
                                <hr style="background-color: black;">
                                <div class="row mt-20">
                                    <div class="col-md-12 col-12 ">
                                        <div class="res-box sm-left custom_fount">
                                            Forgot Password? <a href="{% url 'password_reset' %}" tabindex="5"
                                                class="forgot-password">Reset</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-10">
                                    <div class="col-md-12 col-12">
                                        <div class="res-box sm-left custom_fount">
                                            Don't have an account? <a href="{% url 'user_registration' %}" tabindex="5"
                                                class="forgot-password">Sign up</a>
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

accommodation/account/templates/password_change.html
{% extends 'base_dashboard.html' %}

{% block dashboard_content %}
<style>
    .custom_input{
        background-color: #1f2229;
        border: none;
        border-bottom: solid 1px white;
        color: white;
        width: 100%;
        font-size: large;
    }
    .side_line{
    border-left: solid #0071e3; 
    padding-left: 10px;
    
}
span{
    position: absolute;
    right: 15px;
    transform: translate(0,-50%);
    top: 80%;
    cursor: pointer;
}
.fa{
    font-size: 20px;
    color: #7a797e;
}
</style>
{% if user.is_authenticated %}
<div class="row">
    <div class="col-md-3">
        <div class="act-title">
            <h5 class="side_line">Change Your Password</h5>
        </div>
    </div>
    <div class="col-md-6 col-sm-12 mt-100">
        <div class="form-group">
            
            <div id="description" class="list-details-section">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Old Password</label><br>
                        <input class="custom_input" type="password" name="old_password" id="id_old_password" required="True"><br><br>
                        <!-- <span>
                            <i class="fa fa-eye" id="eye" onclick="toggle()">
                            </i>
                        </span> -->
                    </div>
                    <div class="form-group">
                        <label>New Password</label><br>
                        <input class="custom_input" type="password" name="new_password1" id="id_new_password1" required="True"><br><br>
                        <!-- <span>
                            <i class="fa fa-eye" id="eye" onclick="toggle()">
                            </i>
                        </span> -->
                    </div>
                    <div class="form-group">
                        <label>Confirm Password</label><br>
                        <input class="custom_input" type="password" name="new_password2" id="id_new_password2" required="True"><br><br>
                        <!-- <span>
                            <i class="fa fa-eye" id="eye" onclick="toggle()">
                            </i>
                        </span> -->
                    </div>

                    {% for field in form %}
                        {% for error in field.errors %}
                            <p style="color: red;">{{error}}</p>
                        {% endfor %}
                    {% endfor %}
                    <br>
                    <button class="btn v1" type="submit">Change Password</button>
                </form>
            </div>
            <!-- <br><br>
            <ul>
                <li>password can’t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be a commonly used password.</li>
                <li>Your password can’t be entirely numeric.</li>
            </ul> -->
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
{% endif %}

{% endblock %}

accommodation/account/templates/registration.html
{% extends 'base_account.html' %}
{% block account_content %}

<div class="error-section mt-50 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3  error-text text-center">
                <div class="error-content">
                    {% for message in messages %}
                    <div class="card" style="border-color: #c40000; height: 15%; background-color: black;">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-2 mt-1">
                                    <img class="img-fluid" src="/static/images/warning.png" alt="...">
                                </div>
                                <div class="col-md-10">
                                    <h8 style="color: red">There was a problem</h8><br>
                                    <h8 style="color: red;">{{message}}</h8>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    {% endfor %}
                </div>
                <div class="error-search-container">
                    <div class="card text-light" style="background-color: #1f2229;">
                        <div class="card-body">
                            <h4>Sign up</h4>
                            <hr />
                            <div class="row">
                                <div class="col-md-2"></div>
                                <div class="col-md-8">
                                    <form id="register-form" action="#" method="post">{% csrf_token %}
                                        <div class="form-group">
                                            <label>First Name</label>
                                            <input type="text" name="first_name" id="first_name" tabindex="1"
                                                class="custom_input" value="">
                                        </div>
                                        <div class="form-group">
                                            <label>Last Name</label>
                                            <input type="text" name="last_name" id="last_name" tabindex="1"
                                                class="custom_input" value="">
                                        </div>
                                        <div class="form-group">
                                            <label>Phone Number</label>
                                            <input type="text" name="phone_number" id="phone_number" tabindex="1"
                                                class="custom_input" value="">
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" name="email" id="email" tabindex="1"
                                                class="custom_input" value="">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" name="password" id="password" tabindex="2" class="custom_input">
                                        </div>
                                        <div class="form-group">
                                            <label>Conform Password</label>
                                            <input type="password" name="confirm_password" id="confirm-password"
                                                tabindex="2" class="custom_input">
                                        </div>
                                        <div class="form-group" style="padding-left: 25%;">
                                            <button type="submit" class="btn v1" style="width: 100%;">Sign Up</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-2"></div>
                            </div>
                            <hr style="background-color: black;">
                            <div class="row mt-20">
                                <div class="col-md-12 col-12">
                                    <div class="res-box sm-left custom_fount">
                                        Already registered? <a href="{% url 'login' %}" tabindex="5"
                                            class="forgot-password">Sign in</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}